import type { NextPage } from 'next';
import Head from 'next/head';
import DashboardForm from '../components/DashboardForm';
import Header from '../components/Header';

import { getAccountInfo } from '../services/account.service';
import styles from '../styles/Home.module.css';

const Home: NextPage = ({account}: any) => {
  return (
    <>
      <Head>
        <title>{account.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header brand={account.name} />
      <h1>Hello {account.owner}!</h1>
      <DashboardForm />
    </>
  );
}

export async function getStaticProps() {
  const account = getAccountInfo();

  return {
    props: {
      account,
    },
  }
}

export default Home
