import type { NextPage } from 'next';
import Head from 'next/head';
import {LocalizationProvider} from '@mui/x-date-pickers';
import { AdapterMoment } from '@mui/x-date-pickers/AdapterMoment';
import Box from '@mui/material/Box';

import { getAccountInfo } from '../services/account.service';
import DashboardForm from '../components/DashboardForm';
import Header from '../components/Header';
import { Typography } from '@mui/material';

const Home: NextPage = ({account}: any) => {
  return (
    <>
      <Head>
        <title>{account.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header brand={account.name} />
      <LocalizationProvider dateAdapter={AdapterMoment}>
        <Typography
          variant="h4"
          component="h1"
          textAlign="center"
          paddingTop={2}>
          Hello {account.owner}!
        </Typography>
        <Box display="flex" justifyContent="center"> 
          <DashboardForm />
        </Box>
      </LocalizationProvider>
    </>
  );
}

export async function getStaticProps() {
  const account = getAccountInfo();

  return {
    props: {
      account,
    },
  }
}

export default Home
